### ISSUE TITLE
_(:з)∠)_是我太笨了吗？能不能给个onedrive的范例。。

### ISSUE THREAD

**Issue by NoString** [txperl/JustList#14]
**如果我想设置我的二级域名应该怎么弄？ 把
http_server = WSGIServer(("127.0.0.1", 5000), app)
改为
http_server = WSGIServer(("1.example.com", 8080), app)
**

这是onedrive的设置。。，所谓手动获取，我还需要在config文件中设置我的个人账号密码吗？
https://gitee.com/zhssss/image/raw/master/img/20210409120844.yml

**Comment by txperl** [comment]
### A1
如果想通过自定义域名访问，修改程序中的监听地址是无效的。你需要配置一下 HTTP 服务器（Nginx, Apache 等），让其处理外部请求。具体教程网上有很多，可以自己搜索一下，关键词可以参考「python nginx」等。

### A2
`README.md` 中有写：

```yml
# OneDrive，下列字段位于 ./app/config/onedrive.yml
# 0 为国际版，1 为世纪互联版，填写后程序启动时会引导您手动获取 Refresh Token
accounts:
  OneDrive_INTL:
    - 0
  OneDrive_CN:
    - 1
```

无需填写个人账号及密码，你只要修改「OneDrive_INTL」等值（可以随意填写），以及其相应的 OneDrive 版本代码（0 或 1）即可。之后程序会在第一次启动时引导你获取所需的 Token，这不需要你手动修改。

如果实在搞不清的话，可以就只填写

```yml
accounts:
  OneDrive_INTL:
    - 0
或
accounts:
  OneDrive_CN:
    - 1
```

试一下就有感觉了？hhh

### A3
( *・ω・) 不是你太笨了哦，是我文档确实写得不够细...（（
