### ISSUE TITLE
onedrive国际版不知道怎么填写

### ISSUE THREAD

**Issue by iocoeoqq** [txperl/JustList#22]
onedrive不知道怎么填写
  OneDrive_INTL:
    - 0
  OneDrive_CN:
    - 1
    是这里把，有教程呢

**Comment by txperl** [comment]
```yml
# OneDrive，下列字段位于 ./app/config/onedrive.yml
# 0 为国际版，1 为世纪互联版，填写后程序启动时会引导您手动获取 Refresh Token
accounts:
  OneDrive_INTL:
    - 0
  OneDrive_CN:
    - 1
 ```

例如，如果只想使用 OneDrive 国际版，那可以只保留以下配置：

```yml
accounts:
  OneDrive_INTL:
    - 0
```

其中，`OneDrive_INTL` 是自定义字段，可以更换成想要显示的名称。`- 0` 则是指示此用户为国际版。然后只要启动程序，程序会引导你获取并填写 Code 的。
